FoodDeliveryShop/Controllers/CartController.cs
using FoodDeliveryShop.Models;
using FoodDeliveryShop.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FoodDeliveryShop.Controllers
{
	public class CartController : Controller
	{
		private IProductRepository repository;
		private Cart cart;
		public CartController(IProductRepository repo, Cart cartService)
		{
			this.repository = repo;
			this.cart = cartService;
		}
		public ViewResult Index(string returnUrl)
		{
			return View(new CartIndexViewModel
			{
				Cart = this.cart,
				ReturnUrl = returnUrl
			});
		}
		public RedirectToActionResult AddToCart(int productId, string returnUrl)
		{
			ProductModel? product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
			if (product != null)
			{
				this.cart.AddItem(product, 1);
			}
			return RedirectToAction("Index", new { returnUrl });
		}
		public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
		{
			ProductModel? product = repository.Products.FirstOrDefault(p => p.ProductID == productId);
			if (product != null)
			{
				this.cart.RemoveLine(product);
			}
			return RedirectToAction("Index", new { returnUrl });
		}
		public RedirectToActionResult Clear(string returnUrl)
		{
			this.cart.Clear();
			return RedirectToAction("Index", new { returnUrl });
		}
	}
}

FoodDeliveryShop/Views/Shared/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace FoodDeliveryShop.Views.Shared.Components
{
	public class CartSummaryViewComponent : ViewComponent
	{
		private Models.Cart cart;
		public CartSummaryViewComponent(Models.Cart cartService)
		{
			cart = cartService;
		}
		public IViewComponentResult Invoke()
		{
			return View(cart);
		}
	}
}

FoodDeliveryShop/Views/Shared/Components/NavigationМenuViewComponent.cs
using FoodDeliveryShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace FoodDeliveryShop.Components
{
	public class NavigationМenuViewComponent : ViewComponent
	{
		private IProductRepository repository;

		public NavigationМenuViewComponent(IProductRepository repo)
		{
			repository = repo;
		}

		public IViewComponentResult Invoke() {
			ViewBag.SelectedCategory = RouteData?.Values["category"];
			return View(
				repository.Products
				.Select(x => x.Category)
				.Distinct()
				.OrderBy(x => x));
		} 
	}
}

FoodDeliveryShop/Views/Shared/ProductSummary.cshtml
@using FoodDeliveryShop.Models
@model ProductModel
<div class="card m-1 p-1" style="border-color:dodgerblue; border-width:1.5px;">
	<div class="bg-light p-1">
		<h4>
			@Model.Name
			<span class="badge badge-pill badge-primary" style="float:right;background-color:dodgerblue;color:white">
				<small style="">@Model.Price.ToString("c")</small>
				</span>
		</h4>
	</div>
	<form id="@Model.ProductID" asp-action="AddToCart" asp-controller="Cart" method="post">
		<input type="hidden" asp-for="ProductID" />
		<input type="hidden" name="returnUrl"
			   value="@ViewContext.HttpContext.Request.PathAndQuery()" />
		<span class="card-text p-1">
			@Model.Description
			<button type="submit"
					class="btn btn-success btn-sm" style="float:right">
				Add To Cart
			</button>
		</span>
	</form>
	<div class="card-text p-1">
		@Model.Description
	</div>
</div>

FoodDeliveryShop/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
	<head>
		<meta name="viewport" content="width=device-width" />
		<link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/bootstrap.min.css" />
		<script src="~/lib/jquery/dist/jquery.min.js"></script>
		<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
		<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
		<title>@ViewBag.Title</title>
	</head>
	<body class="m-1 p-1">
		<div class="bg-info p-2 row">
		<div class="col">
			<h4>@ViewBag.Title</h4>
		</div>
		<div class="col-2">
			<a class="btn btn-sm btn-primary"
			   asp-action="Logout" asp-controller="Account">Log Out</a>
		</div>
	</div>
	@if (TempData["message"] != null)
	{
		<div class="alert alert-success">@TempData["message"]</div>
	}
	@RenderBody()
	</body>
</html>

FoodDeliveryShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - FoodDeliveryShop</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/FoodDeliveryShop.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FoodDeliveryShop</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						@await Component.InvokeAsync("NavigationМenu") 
					</ul>
				</div>
				<div class="text-right">
					@await Component.InvokeAsync("CartSummary")
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2023 - FoodDeliveryShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<!--\
	<div id="categories" class="col-3">

		</div>
							<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
						</li>
						-->